# ====================
# Messages Configuration
# ====================

messages:

  # Set a global prefix for all messages
  prefix: '<bold><gold>[SPEEDRUN]</gold></bold>'

  # Help message for non-administrative players
  helpMessage:
    - '<gold><st>                            </st></gold><white><bold> SPEEDRUN HELP </bold></white><gold><st>                           </st></gold>'
    - '<gold><click:suggest_command:/objectives>/objectives</click></gold> <black>-</black> View all speedrun objectives'
    - '<gold><click:suggest_command:/team>/team [teamName]</click></gold> <black>-</black> Join a specific team.'
    - '<gold><st>                                                                                </st></gold>'

  # Team Messages
  teamJoinMessage: '<prefix> You joined: <team_name>'
  teamCooldownMessage: '<prefix> Please wait a few seconds before changing your team.'
  teamHelp: '<prefix> Please use /team [teamName] to join a team.'
  alreadyOnTeam: '<prefix> You are already on this team!'
  teamIsFull: '<prefix> This team is full!'
  teamNotFound: '<prefix> Cannot find team: <team_name>'

  # Speedrun Start/Stop Messages
  start: <prefix> The speedrun has started!<newline><prefix> You have <bold><gold><time>
    minutes</gold></bold> to complete the objectives!<newline><prefix> Please type
    <click:run_command:'/objectives'><hover:show_text:'<bold><gold>Click here to view
    your objectives</gold></bold>'><bold><gold>/objectives</gold></bold></hover></click>
    to view your objectives.
  forceStop: '<prefix> The game has ended!<newline><prefix> The winner is inconclusive.'
  winner: '<prefix> The game has ended!<newline><prefix> The winner is: <winner>'
  timeUp: '<prefix> The game has ended! Time has run out.<newline><prefix> The team
    with the most points is: <winner>'

  # Objective Messages
  objectiveComplete: '<prefix> Objective Complete: <bold><gold><objective_type> <target></gold></bold><newline><prefix>
    Your team has earned <bold><gold><points> points</gold></bold>!'
  objectiveCompleteNumber: '<prefix> Objective Complete: <bold><gold><objective_type>
    <number> <target></gold></bold><newline><prefix> Your team has earned <bold><gold><points>
    point(s)</gold></bold>!'

  # Error Messages
  error:
    invalidArguments: '<prefix> Invalid Arguments! Usage: <usage>'
    illegalArgument: '<prefix> Illegal Argument! <illegal_arg> is not a <expected_type>.'
    outOfBounds: '<prefix> Illegal Argument! <illegal_arg> is out of bounds for <object>.'


  # Admin Messages
  admin:

    # Help message for administrative players
    helpMessage:
      p1:
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
        - '<gold><st>                             </st></gold><white><bold> ADMIN HELP 1/4 </bold></white><gold><st>                        </st></gold><bold><click:run_command:/help 2><hover:show_text:''<bold>NEXT PAGE</bold>''>></hover></click></bold>'
        - '<gold><click:suggest_command:/speedrun addObjective>/speedrun addObjective [objectiveType] [target] <-flag(s)></click></gold> <black>-</black> Add an objective.'
        - '<gold><click:suggest_command:/speedrun objectives>/speedrun objectives</click></gold> <black>-</black> List all objectives.'
        - '<gold><click:suggest_command:/speedrun remObjective>/speedrun remObjective [number]</click></gold> <black>-</black> Remove an objective according to number on objective list.'
        - '<gold><click:suggest_command:/speedrun setSeed>/speedrun setSeed [seed]</click></gold> <black>-</black> Set the map seed.'
        - '<gold><click:suggest_command:/speedrun getSeed>/speedrun getSeed</click></gold> <black>-</black> Get the map seed.'
        - '<gold><click:suggest_command:/speedrun setBorder>/speedrun setBorder [radius]</click></gold> <black>-</black> Set the map border.'
        - '<gold><st>                                                                                </st></gold>'
      p2:
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
        - '<bold><click:run_command:/help 1><hover:show_text:''<bold>PREVIOUS PAGE</bold>''><</hover></click></bold><gold><st>                           </st></gold><white><bold> ADMIN HELP 2/4 </bold></white><gold><st>                        </st></gold><bold><click:run_command:/help 3><hover:show_text:''<bold>NEXT PAGE</bold>''>></hover></click></bold>'
        - '<gold><click:suggest_command:/speedrun getBorder>/speedrun getBorder</click></gold> <black>-</black> Get the map border.'
        - '<gold><click:suggest_command:/speedrun setTimeLimit>/speedrun setTimeLimit [minutes]</click></gold> <black>-</black> Set the game time limit.'
        - '<gold><click:suggest_command:/speedrun getTimeLimit>/speedrun getTimeLimit</click></gold> <black>-</black> Get the game time limit.'
        - '<gold><click:suggest_command:/speedrun setSpawnRadius>/speedrun setSpawnRadius [number]</click></gold> <black>-</black> Set team spawn radius from (0, 0).'
        - '<gold><click:suggest_command:/speedrun getSpawnRadius>/speedrun getSpawnRadius</click></gold> <black>-</black> Get team spawn radius from (0, 0).'
        - '<gold><st>                                                                                </st></gold>'
        - ''
      p3:
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
        - '<bold><click:run_command:/help 2><hover:show_text:''<bold>PREVIOUS PAGE</bold>''><</hover></click></bold><gold><st>                           </st></gold><white><bold> ADMIN HELP 3/4 </bold></white><gold><st>                        </st></gold><bold><click:run_command:/help 4><hover:show_text:''<bold>NEXT PAGE</bold>''>></hover></click></bold>'
        - '<gold><click:suggest_command:/speedrun setTeamSize>/speedrun setTeamSize [number]</click></gold> <black>-</black> Set the player limit for each team.'
        - '<gold><click:suggest_command:/speedrun getTeamSize>/speedrun getTeamSize</click></gold> <black>-</black> Get the player limit for each team.'
        - '<gold><click:suggest_command:/speedrun setPointLimit>/speedrun setPointLimit [number]</click></gold> <black>-</black> Set the points required for a team to win.'
        - '<gold><click:suggest_command:/speedrun getPointLimit>/speedrun getPointLimit</click></gold> <black>-</black> Get the points required for a team to win.'
        - '<gold><st>                                                                                </st></gold>'
        - ''
      p4:
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''
        - '<bold><click:run_command:/help 3><hover:show_text:''<bold>PREVIOUS PAGE</bold>''><</hover></click></bold><gold><st>                           </st></gold><white><bold> ADMIN HELP 4/4 </bold></white><gold><st>                          </st></gold>'
        - '<gold><click:suggest_command:/speedrun team>/speedrun team [teamName]</click></gold> <black>-</black> Join a specific team.'
        - '<gold><click:suggest_command:/speedrun resetAttributes>/speedrun resetAttributes</click></gold> <black>-</black> Reset all settings back to default.'
        - '<gold><click:suggest_command:/speedrun start>/speedrun start</click></gold> <black>-</black> Generate world and start the game.'
        - '<gold><click:suggest_command:/speedrun stop>/speedrun stop</click></gold> <black>-</black> Force end the game.'
        - '<gold><st>                                                                                </st></gold>'
        - ''
        - ''
        - ''

    objectiveAdded: '<prefix> Objective Added: <bold><gold><objective_type> <target></gold></bold>'
    objectiveAddedPoints: '<prefix> Objective Added: <bold><gold><objective_type>
      <target></gold></bold> - <points> points'
    objectiveAddedNumber: '<prefix> Objective Added: <bold><gold><objective_type>
      <number> <target></gold></bold>'
    objectiveAddedPointsNumber: '<prefix> Objective Added: <bold><gold><objective_type>
      <number> <target></gold></bold> - <points> points'
    objectiveRemoved: '<prefix> Objective Removed: <bold><gold><objective_type> <target></gold></bold>'
    timeLimitSet: '<prefix> Time limit set to: <bold><gold><time_limit> Minute(s)</gold></bold>'
    timeLimit: '<prefix> Time Limit: <bold><gold><time_limit> Minute(s)</gold></bold>'
    teamSizeLimitSet: '<prefix> Team size limit set to: <bold><gold><size_limit></gold></bold>'
    teamSizeLimit: '<prefix> Team Size Limit: <bold><gold><size_limit></gold></bold>'
    seedSet: '<prefix> World seed has been set to: <bold><gold><seed></gold></bold>'
    seed: '<prefix> Seed: <bold><gold><seed></gold></bold>'
    worldBorderSet: '<prefix> World border has been set to: <bold><gold><world_border></gold></bold>'
    worldBorder: '<prefix> World Border: <bold><gold><world_border></gold></bold>'
    spawnRadiusSet: '<prefix> Spawn radius has been set to: <bold><gold><spawn_radius></gold></bold>'
    spawnRadius: '<prefix> Spawn Radius: <bold><gold><spawn_radius></gold></bold>'
    pointLimitSet: '<prefix> Point limit set to: <bold><gold><point_limit></gold></bold>'
    pointLimit: '<prefix> Point Limit: <bold><gold><point_limit></gold></bold>'
    gameAlreadyStarted: '<prefix> The game has already started!'
    gameStarted: '<prefix> You have started the speedrun!'
    worldGenerating: '<prefix> Generating world... Please wait.'
    worldGenerated: '<prefix> World generated! Please enter <bold><gold>/speedrun start</gold></bold> again to 
      start the game.'
    resetAttributes: '<prefix> All attributes have been reset.'


# ====================
# Timer Configuration
# ====================

timer:

  # Timer Settings
  interval: 1
  disable: false

  # Timer Messages
  title: '<bold><gold>KSU SPEEDRUN</gold></bold>'
  timeLeft: '<white>Time Remaining:</white> <bold><gold><time_remaining></gold></bold>'
  gameOverMessage: '<white><bold>GAME OVER!</bold></white>'

# ====================
# Team Configuration
# ====================

teams:

  # Team Inventory Settings
  inventory:
    title: <bold><yellow>SELECT A TEAM:</yellow></bold>
    cooldown: 5

  # Team Definitions - Add and Remove Teams Here
  white:
    name: '<!italic><white><bold>WHITE TEAM</bold></white>'
    item: WHITE_WOOL
    lore: '<!italic><white>Click here to join <bold>WHITE TEAM</bold>!</white>'
  orange:
    name: '<!italic><gold><bold>ORANGE TEAM</bold></gold>'
    item: ORANGE_WOOL
    lore: '<!italic><white>Click here to join </white><bold><gold>ORANGE TEAM</gold></bold><white>!</white>'
  magenta:
    name: '<!italic><color:#ff00ff><bold>MAGENTA TEAM</bold></color>'
    item: MAGENTA_WOOL
    lore: '<!italic><white>Click here to join </white><bold><color:#ff00ff>MAGENTA
      TEAM</color></bold><white>!</white>'
  light_blue:
    name: '<!italic><color:#00ffff><bold>LIGHT BLUE TEAM</bold></color>'
    item: LIGHT_BLUE_WOOL
    lore: '<!italic><white>Click here to join </white><bold><color:#00ffff>LIGHT BLUE
      TEAM</color></bold><white>!</white>'
  yellow:
    name: '<!italic><yellow><bold>YELLOW TEAM</bold></yellow>'
    item: YELLOW_WOOL
    lore: '<!italic><white>Click here to join </white><bold><yellow>YELLOW TEAM</yellow></bold><white>!</white>'
  lime:
    name: '<!italic><green><bold>LIME TEAM</bold></green>'
    item: LIME_WOOL
    lore: '<!italic><white>Click here to join </white><bold><green>LIME TEAM</green></bold><white>!</white>'
  pink:
    name: '<!italic><color:#ff85c8><bold>PINK TEAM</bold></color>'
    item: PINK_WOOL
    lore: '<!italic><white>Click here to join </white><bold><color:#ff85c8>PINK TEAM</color></bold><white>!</white>'
  gray:
    name: '<!italic><dark_gray><bold>GRAY TEAM</bold></dark_gray>'
    item: GRAY_WOOL
    lore: '<!italic><white>Click here to join </white><bold><dark_gray>GRAY TEAM</dark_gray></bold><white>!</white>'
  light_gray:
    name: '<!italic><gray><bold>LIGHT GRAY TEAM</bold></gray>'
    item: LIGHT_GRAY_WOOL
    lore: '<!italic><white>Click here to join </white><bold><gray>LIGHT GRAY TEAM</gray></bold><white>!</white>'
  cyan:
    name: '<!italic><dark_aqua><bold>CYAN TEAM</bold></dark_aqua>'
    item: CYAN_WOOL
    lore: '<!italic><white>Click here to join </white><bold><dark_aqua>CYAN TEAM</dark_aqua></bold><white>!</white>'
  purple:
    name: '<!italic><dark_purple><bold>PURPLE TEAM</bold></dark_purple>'
    item: PURPLE_WOOL
    lore: '<!italic><white>Click here to join </white><bold><dark_purple>PURPLE TEAM</dark_purple></bold><white>!</white>'
  blue:
    name: '<!italic><dark_blue><bold>BLUE TEAM</bold></dark_blue>'
    item: BLUE_WOOL
    lore: '<!italic><white>Click here to join </white><bold><dark_blue>BLUE TEAM</dark_blue></bold><white>!</white>'
  brown:
    name: '<!italic><color:#964b00><bold>BROWN TEAM</bold></color>'
    item: BROWN_WOOL
    lore: '<!italic><white>Click here to join </white><bold><color:#964b00>BROWN TEAM</color></bold><white>!</white>'
  green:
    name: '<!italic><dark_green><bold>GREEN TEAM</bold></dark_green>'
    item: GREEN_WOOL
    lore: '<!italic><white>Click here to join </white><bold><dark_green>GREEN TEAM</dark_green></bold><white>!</white>'
  red:
    name: '<!italic><dark_red><bold>RED TEAM</bold></dark_red>'
    item: RED_WOOL
    lore: '<!italic><white>Click here to join </white><bold><dark_red>RED TEAM</dark_red></bold><white>!</white>'
  black:
    name: '<!italic><black><bold>BLACK TEAM</bold></black>'
    item: BLACK_WOOL
    lore: '<!italic><white>Click here to join </white><bold><black>BLACK TEAM</black></bold><white>!</white>'

# ====================
# World Configuration
# ====================

world:

  # Delete previously generated "speedrunworld" upon plugin startup?
  deleteOnStart: true

  # Spawn point when players initially join the server (while the speedrun is not started)
  spawnPoint:
    world: 'world'
    x: 0.0
    y: 150.0
    z: 0.0
    pitch: 0.0
    yaw: 0.0

# ====================
# Structure Configuration
# ====================

structureLocations:

  # Define Average Y-Coordinate for each Structure or Set Detection Radius
  # For future updates, you may manually add structures according to their
  # official org.Bukkit.generator.structure.Structure name

  PILLAGER_OUTPOST:
    averageYCoordinate: ground
    radius: 30
    height: 25
  MINESHAFT:
    averageYCoordinate: 0
    radius: 100
    height: 20
  MINESHAFT_MESA:
    averageYCoordinate: ground
    radius: 30
    height: 10
  MANSION:
    averageYCoordinate: ground
    radius: 30
    height: 25
  JUNGLE_PYRAMID:
    averageYCoordinate: ground
    radius: 10
    height: 15
  DESERT_PYRAMID:
    averageYCoordinate: ground
    radius: 15
    height: 20
  IGLOO:
    averageYCoordinate: ground
    radius: 4
    height: 5
  SHIPWRECK:
    averageYCoordinate: 50
    radius: 15
    height: 10
  SHIPWRECK_BEACHED:
    averageYCoordinate: ground
    radius: 15
    height: 10
  SWAMP_HUT:
    averageYCoordinate: ground
    radius: 4
    height: 5
  STRONGHOLD:
    averageYCoordinate: 0
    radius: 75
    height: 30
  MONUMENT:
    averageYCoordinate: 45
    radius: 30
    height: 16
  OCEAN_RUIN_COLD:
    averageYCoordinate: 45
    radius: 10
    height: 5
  OCEAN_RUIN_WARM:
    averageYCoordinate: 45
    radius: 10
    height: 5
  FORTRESS:
    averageYCoordinate: 15
    radius: 75
    height: 50
  NETHER_FOSSIL:
    averageYCoordinate: 35
    radius: 5
    height: 4
  END_CITY:
    averageYCoordinate: ground
    radius: 30
    height: 100
  BURIED_TREASURE:
    averageYCoordinate: ground - 4
    radius: 2
    height: 1
  BASTION_REMNANT:
    averageYCoordinate: 35
    radius: 40
    height: 45
  VILLAGE_PLAINS:
    averageYCoordinate: ground
    radius: 30
    height: 8
  VILLAGE_DESERT:
    averageYCoordinate: ground
    radius: 30
    height: 8
  VILLAGE_SAVANNA:
    averageYCoordinate: ground
    radius: 30
    height: 8
  VILLAGE_SNOWY:
    averageYCoordinate: ground
    radius: 30
  VILLAGE_TAIGA:
    averageYCoordinate: ground
    radius: 30
    height: 8
  RUINED_PORTAL:
    averageYCoordinate: ground
    radius: 30
    height: 8
  RUINED_PORTAL_DESERT:
    averageYCoordinate: ground
    radius: 30
    height: 8
  RUINED_PORTAL_JUNGLE:
    averageYCoordinate: ground
    radius: 5
    height: 6
  RUINED_PORTAL_SWAMP:
    averageYCoordinate: ground
    radius: 5
    height: 6
  RUINED_PORTAL_MOUNTAIN:
    averageYCoordinate: ground
    radius: 5
    height: 6
  RUINED_PORTAL_OCEAN:
    averageYCoordinate: ground
    radius: 5
    height: 6
  RUINED_PORTAL_NETHER:
    averageYCoordinate: 35
    radius: 5
    height: 6
  ANCIENT_CITY:
    averageYCoordinate: -51
    radius: 100
    height: 50
  TRAIL_RUINS:
    averageYCoordinate: ground - 8
    radius: 5
    height: 10
  TRIAL_CHAMBERS:
    averageYCoordinate: -30
    radius: 100
    height: 30